### ISSUE TITLE
zoom links uses document.write, removes schoology header

### ISSUE THREAD

**Issue by goombamaui** [Harker-Hackers/schoology-extension#5]
Currently, the zoomlinks schoology page has no header making it hard to navigate out of it. In addition, it never fully loads, but instead keeps playing the blue loading circle.

**Comment by gadhagod** [comment]
Fixed in https://github.com/Harker-Hackers/schoology-extension/commit/73162810193b0c01142c4fb24c80e8a1e901d2d5.
